== xd

The xd crossword corpus started as a model "small data" project, testing my thesis that simple file formats and obsessive curation are https://en.wikipedia.org/wiki/The_Unreasonable_Effectiveness_of_Mathematics_in_the_Natural_Sciences[unreasonably effective] in the data sciences.

Since the project did uncover some http://www.slate.com/articles/life/gaming/2016/03/how_to_spot_a_plagiarized_crossword.html[malfeasance in the crossword industry], it seems important to have an ongoing process for analyzing crosswords, to discourage copytheft and programmatic puzzle generation.

The xd link:/doc[design] is intentionally textpunk and therefore platform-agnostic. Anyone can browse, contribute, or consume data with minimal effort.

== Browse

- a link:/pub[map of all crosswords] in the corpus
- the link:/pub/clue[most popular clues]
- the link:/pub/word[most popular words] (answers)
- link:/pub/usa2016-03-05[/pub/usa2016-03-05]: a specific puzzle, in this case from USAToday on the Saturday that #gridgate blew up

== Download

- link:/pub/xd-tsv.zip[xd-tsv.zip]: all xd metadata in link:/doc/format#tsv[.tsv format]
- link:/pub/xd-public.zip[xd-public.zip]: all publicly released puzzles in link:/doc/format#xd[.xd format]

== Contribute

Submit crosswords for analysis or inclusion to submit@xd.saul.pw (as attachments: .puz, .ipuz, .xd, .pdf, or .zip of these). link:/submit[More Info]

The basic collection/analysis/presentation pipeline is operational.  This pipeline needs to be thoroughly documented.

xd needs a legal entity (for the content) and a succession plan.


=== Help improve the curation, analysis, or presentation

- View the entire codebase at http://github.com/century-arcade/xd[github.com/century-arcade/xd]

