# Import everything from within xdfile, dictated by __all__ within xdfile.
# The inline comment causes pyflakes to ignore this line. It complains
# about the * import, which isn't a problem.
from xdfile import *  # NOQA

publishers = {
    'unk': 'unknown',
    'che': 'chronicle',
    'ch': 'chicago',
    'cs': 'crossynergy',
    'pp': 'wapost',
    'wsj': 'wsj',
    'rnr': 'rocknroll',
    'nw': 'newsday',
    'nyt': 'nytimes',
    'tech': 'nytimes',
    'tm': "time",
    'nfl': "cbs",
    'cn': "crosswordnation",
    'vwl': 'nytimes',
    'nyk': 'nytimes',
    'la': 'latimes',
    'nys': 'nysun',
    'pzz': 'puzzazz',
    'nyh': 'nyherald',
    'lt': 'london',
    'pa': 'nytimes',
    'pk': 'king',
    'nym': 'nymag',
    'db': 'dailybeast',
    'awm': 'threeacross',
    'rp': 'rexparker',
    'wp': 'wapost',
    'nl': 'lampoon',
    'tmdcr': 'tribune',
    'kc': 'kcstar',
    'mg': 'mygen',
    'atc': 'crossroads',
    'onion': 'onion',
    'mm': 'aarp',
    'ue': 'universal',
    'ut': 'universal',
    'up': 'universal',
    'us': 'universal',
    'um': 'universal',
    'ub': 'universal',
    'ss': 'simonschuster',
    'sl': 'slate',
    'ana': 'nytimes',
}
