#!/usr/bin/env python

import os.path
import sys
import zipfile

from ccxml2xd import parse_ccxml
from uxml2xd import parse_uxml
from ujson2xd import parse_ujson
from puz2xd import parse_puz
from xwordinfo2xd import parse_xwordinfo


def main():
    rawzip = sys.argv[1]
    xdzip = sys.argv[2]

    funcs = [ parse_ccxml, parse_uxml, parse_ujson, parse_puz, parse_xwordinfo ]
    rawzf = zipfile.ZipFile(rawzip, 'r')
    xdzf = zipfile.ZipFile(xdzip, 'w')

    for zi in rawzf.infolist():
        converted = False
        errors = [ ]
        print zi.filename,
        base, ext = os.path.splitext(zi.filename)
        if ext == ".pdf":
            continue

        for f in funcs: 
            try:
                xd = f(rawzf.read(zi))
                xdstr = xd.to_unicode().encode("utf-8")
               

                xdzi = zipfile.ZipInfo(base + ".xd")
                xdzi.external_attr = 0444 << 16L
                xdzi.compress_type = zipfile.ZIP_DEFLATED
                xdzf.writestr(xdzi, xdstr)
                converted = True
                print f.__name__, "converted (%s bytes)" % len(xdstr)
            except Exception, e:
                errors.append("%s: %s" % (f.__name__, str(e)))

        if not converted:
            print
            print "\n".join(errors)

if __name__ == "__main__":
    main()

