#!/usr/bin/env python

import xdfile
import flipgrid
import os

def collapse_whitespace(s):
    return u"".join(x.strip() for x in s.splitlines()).strip()

def rewrite_corpus(corpus):
    for fn, xd in sorted(corpus.items()):
        if not xd.grid:
            continue
        
#        xdfile.clean_headers(xd)
        fullfn = xd.filename
#        outxd = xd.to_unicode(emit_clues=False)
        outxd = flipgrid.flipgrid(xd)
        outxd.filename = "transposed/" + xd.filename
#        if collapse_whitespace(outxd) != collapse_whitespace(inxd):
#            print fullfn, "differs when re-emitted"
        try:
            basedir, _fn = os.path.split(outxd.filename)
            try:
                os.makedirs(basedir)
            except:
                pass
            file(outxd.filename, 'w').write(outxd.to_unicode().encode("utf-8"))
        except Exception, e:
            print str(e)


            
if __name__ == "__main__":
    corpus = xdfile.main_load()
    rewrite_corpus(corpus)
