#!/usr/bin/env python

import xdfile
import os

def collapse_whitespace(s):
    return u"".join(x.strip() for x in s.splitlines()).strip()

def rewrite_corpus(corpus):
    for fullfn, xd in corpus.items():
        inxd = file(fullfn).read().decode("utf-8")
        outxd = xd.to_unicode()
        if collapse_whitespace(outxd) != collapse_whitespace(inxd):
            print fullfn, "differs when re-emitted"
            try:
                file(fullfn, 'w').write(outxd.encode("utf-8"))
            except Exception, e:
                print str(e)


            
if __name__ == "__main__":
    corpus = xdfile.main_load()
    rewrite_corpus(corpus)
